### ISSUE TITLE
FR: "ALL" context if long press

### ISSUE THREAD

**Issue by saya6k** [diesphink/grocy-tablet#1]
Hi, it's really good work! I love it!

I also adopted this in my Fully Kiosk wall pad.

I understand why you don't add consume "ALL" since it doesn't fit on Tablet interface.

I think using plus button long press as "ALL" or fast increase is quiet common practice for tablet.

In that way I can handle my rotten tomatoes much better :)

**Comment by diesphink** [comment]
Hi, sorry about the delay, for some reason the issues went unnoticed.

Consume ALL should be a nice addition, I'm definitely down to explore adding that in.
