### ISSUE TITLE
FR: Option to view parent/child product

### ISSUE THREAD

**Issue by saya6k** [diesphink/grocy-tablet#2]
And I want the option to see parent / child product.

I'm using parent product only in genuine dashboard but I see both parent and child product in Grocy-Tablet.

I wish there are option.

**Comment by diesphink** [comment]
Good point, I'm not using parent/child yet on my installation, but was pondering about start using for a few products.

You said you use just parent, does it mean that you just wish there was an option to filter the children out?

What I was visualizing was something like tapping a parent to open a dialog with the children for picking which one to adjust, as I would use that for products that we have a lot of flavor variations, like frozen fruit pulp.

**Comment by saya6k** [comment]
Maybe option to only see parent or child? Parent are more used often, but sometimes it is better to see only child. Both option will be fine, like checkbox or dropdown.
